---

- hosts: all
  become: true
  tasks:

  - name: actualizar repositorios
    apt:
      update_cache: yes

  - name: instalar paquete apache2
    apt:
      name: apache2
      state: latest

  - name: añadir soporte php para apache
    apt:
      name: libapache2-mod-php
      state: latest
